### ISSUE TITLE
[EN][Cata][Outlands][Hellfire Peninsula] Disrupt Their Reinforcements

### ISSUE THREAD

**Issue by Illusie** [NRG-Wow/NRGWow-Bugtracker#34] opened 2018-07-21 13:24 UTC
[//]: #  (Only reports in english will be allowed. and specific issues. everything like "ZOMG NOTHING WORKS" will be ignored / deleted)

**Reporter(Player/Character) Name**: ---

**Description**: Collected 8 Demonic Rune Stone, Tried detonate Portal Kaalez
Nothing happen

**Current behaviour**: ^

**Expected behaviour**: you should able detonate portals.
https://www.youtube.com/watch?v=pld6UarEKpc

**Steps to reproduce the problem**:

1.  take quest, kill 8 monsters nearby portal loot quest item try detonate portal

**Comment by NRG-Wow** [comment] 2018-08-02 13:33
duplicate of #17

**Closed as completed by NRG-Wow** 2018-08-02 13:33 UTC
