### ISSUE TITLE
[CATA][Dungeon][The Oculus]

### ISSUE THREAD

**Issue by GajicMilos** [NRG-Wow/NRGWow-Bugtracker#200] opened 2018-08-26 14:37 UTC
**Reporter(Player/Character) Name**:Velhaera

**Description**: Last boss isnt spawning, instead the loot is found as if he was already killed, and it can be looted, but is rendering Achievements for The Oculus undoable. Tried it twice, first 3 bosses are doable and fine, but the last one wont spawn.

**Comment by Wilcalaf** [comment] 2018-08-27 00:22
Duplicate of #182

**Closed as completed by Wilcalaf** 2018-08-27 00:22 UTC
Labels: lowPrio
