### ISSUE TITLE
[CATA][Dungeon][Culling of Stratholme]

### ISSUE THREAD

**Issue by GajicMilos** [NRG-Wow/NRGWow-Bugtracker#199] opened 2018-08-26 14:35 UTC
**Reporter(Player/Character) Name**:Velhaera

**Description**: You can speak to Arthas once you come in the dungeon, however he doesnt move or do anything, and if you go inside Stratholme all the mobs are not killable so you cannot progress through dungeon. I also tried it without and with doing Chromie`s quest but it didnt change.

**Comment by Wilcalaf** [comment] 2018-08-27 00:13
Duplicate of #190

**Closed as completed by Wilcalaf** 2018-08-27 00:13 UTC
