### ISSUE TITLE
[WOTLK][Quests][Sholazar Basin] The Mist Isn't Listening (QuestID: 12538)

### ISSUE THREAD

**Issue by Gubbyfishy** [NRG-Wow/NRGWow-Bugtracker#158] opened 2018-08-12 21:59 UTC
**Reporter(Player/Character) Name**: Hundoslavus

**Description**: All the Gorlocs in Mistwhisper Refuge are classified as "Invalid Targets", despite being hostile and Oracles Faction set to "At War".

**Current behaviour**: All Gorlocs cannot be attacked due to being "Invalid Targets", regardless of faction standing and setting.

**Expected behaviour**: You should be able to attack the Gorlocs without issue.

Will edit later to find relevant NPC ids

**Comment by Wilcalaf** [comment] 2018-08-13 19:31
Duplicate of #28

**Closed as completed by Wilcalaf** 2018-08-13 19:31 UTC
