### ISSUE TITLE
[CATA][Total War][Twilight Highlands] Wildhammer Keg not clickable

### ISSUE THREAD

**Issue by virpyre** [NRG-Wow/NRGWow-Bugtracker#108] opened 2018-08-01 16:03 UTC
**Reporter(Player/Character) Name**: Torgaun

**Description**: Unable to click on [Wildhammer Keg](http://www.wowhead.com/npc=46551/wildhammer-keg-quest-tracker) to smash them for the quest [Total War](http://www.wowhead.com/quest=28872/total-war).

**Current behaviour**:  When you try to click on them, the is no gear icon shown.

**Expected behaviour**:  You should be able to click on the [Wildhammer Keg](http://www.wowhead.com/npc=46551/wildhammer-keg-quest-tracker), then the keg gets destroyed.

**Steps to reproduce the problem**:
1. .quest add 28872
2. Try to click on [Wildhammer Keg](http://www.wowhead.com/npc=46551/wildhammer-keg-quest-tracker _NOTE: You cant smash the barrels if you are in combat._

**Comment by NRG-Wow** [comment] 2018-08-01 16:23
Duplicate of #96

**Closed as completed by NRG-Wow** 2018-08-01 16:23 UTC
