### ISSUE TITLE
[WOTLK][Quests][Basin Sholazar] The Most Isn't Listening

### ISSUE THREAD

**Issue by Cannonbow** [NRG-Wow/NRGWow-Bugtracker#174] opened 2018-08-17 18:01 UTC
Reporter Name:Cannonbow

Description: I can't hit the enemy his name is called mist whisper warrior it says interrupted invalid target 

Expected behaviour: I should hit the enemy and kill him normally 

Steps to reproduce the problem:
1.make a horde char
2.accept the quest
3.kill those 12 mist whisper 
4.finish the quest and take reward

**Comment by Wilcalaf** [comment] 2018-08-30 02:54
Duplicate of #28

**Closed as completed by Wilcalaf** 2018-08-30 02:54 UTC
